import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv(r"D:\4 SLOT\FODS\AT 3\student_performance.csv")
print("Student Performance Dataset")
print(data)
print("\nDataset Information")
print(data.info())
print("\nStatistical Summary")
print(data.describe())
print("\nMissing Values")
print(data.isnull().sum())
print("\nResult Count")
print(data["Result"].value_counts())
print("\nAverage Attendance:", data["Attendance"].mean())
print("Average Study Hours:", data["Study_Hours"].mean())
print("Average Internal Marks:", data["Internal_Marks"].mean())
plt.figure(figsize=(5,4))
plt.hist(data["Attendance"], bins=5)
plt.title("Attendance Distribution")
plt.xlabel("Attendance")
plt.ylabel("Number of Students")
plt.show()

plt.figure(figsize=(5,4))
plt.hist(data["Study_Hours"], bins=5)
plt.title("Study Hours Distribution")
plt.xlabel("Study Hours")
plt.ylabel("Number of Students")
plt.show()

plt.figure(figsize=(5,4))
plt.hist(data["Internal_Marks"], bins=5)
plt.title("Internal Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Number of Students")
plt.show()

plt.figure(figsize=(5,4))
data["Result"].value_counts().plot(kind="bar")
plt.title("Student Result")
plt.xlabel("Result")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(5,4))
plt.scatter(data["Study_Hours"], data["Internal_Marks"])
plt.title("Study Hours vs Internal Marks")
plt.xlabel("Study Hours")
plt.ylabel("Internal Marks")
plt.show()

print("\nCorrelation Matrix")
print(data[["Attendance","Study_Hours","Internal_Marks"]].corr())
